require 'httparty'

require 'laziness/api/base'
require 'laziness/api/auth'
require 'laziness/api/channels'
require 'laziness/api/chat'
require 'laziness/api/conversations'
require 'laziness/api/groups'
require 'laziness/api/im'
require 'laziness/api/oauth'
require 'laziness/api/rtm'
require 'laziness/api/users'
